- name: Setup Apache Server
  hosts: localhost
  become: yes
  tasks:
    - name: Install Apache2 on Ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"
      notify: 
        - Install Apache2 on Ubuntu

    - name: Install Httpd on Amazon
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == "Amazon"
      notify:
        - Install Httpd on Amazon

    - name: Install Httpd on Redhat OS
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == "RedHat"
      notify:
        - Install Httpd on Redhat OS

  handlers:
    - name: Install Apache2 on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Install Httpd on Amazon
      service:
        name: httpd
        state: started
        enabled: yes
         
    - name: Install Httpd on Redhat OS
      service:
        name: httpd
        state: started
        enabled: yes